### ISSUE TITLE
Hello Farzan,

### ISSUE THREAD

**Issue by puneethkum** [FarzanHajian/CreateSwap#1]

**Comment by puneethkum** [comment]
I am getting some syntax error:

python swapfile.py -f myswapfile -s 200
  File "swapfile.py", line 65
    print ('{:40.40}'.format(message), end=end_char, flush=True)
                                          ^
SyntaxError: invalid syntax

do you know ? it seems like its good but still getting syntax error issue

**Comment by FarzanHajian** [comment]
Hi @puneethkum

Sorry for my delayed response. The error occurs because use Python 2 and as I pointed in the "read me" file, this script is tailored to Python 3. The mentioned syntax is understood solely by Python 3.
I will prepare a separate script for Python 2.

Thanks
